on: [push]

name: Run unit tests

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Get to the right branch
      uses: actions/checkout@v3

    - name: Set up Node
      uses: actions/setup-node@v2

    - name: Restore the node modules
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: modules-${{ hashFiles('**/package.json') }}

    - name: Update NPM packages
      run: npm i --include=dev

    - name: Run tests
      run: node --experimental-vm-modules node_modules/jest/bin/jest.js --testTimeout=120000
      env:
        GITHUB_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
